In [2]:
# importing the required libraries
import sys
import numpy as np
import pandas as pd
import seaborn as sns
import pickle
%matplotlib inline 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import sklearn.metrics as metrics
import warnings
warnings.filterwarnings('ignore')

In [3]:
# importing the dataset
dataset = pd.read_csv("flightdata.csv")

In [4]:
# Analysing the data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11231 entries, 0 to 11230
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   YEAR                 11231 non-null  int64  
 1   QUARTER              11231 non-null  int64  
 2   MONTH                11231 non-null  int64  
 3   DAY_OF_MONTH         11231 non-null  int64  
 4   DAY_OF_WEEK          11231 non-null  int64  
 5   UNIQUE_CARRIER       11231 non-null  object 
 6   TAIL_NUM             11231 non-null  object 
 7   FL_NUM               11231 non-null  int64  
 8   ORIGIN_AIRPORT_ID    11231 non-null  int64  
 9   ORIGIN               11231 non-null  object 
 10  DEST_AIRPORT_ID      11231 non-null  int64  
 11  DEST                 11231 non-null  object 
 12  CRS_DEP_TIME         11231 non-null  int64  
 13  DEP_TIME             11124 non-null  float64
 14  DEP_DELAY            11124 non-null  float64
 15  DEP_DEL15            11124 non-null 

In [5]:
dataset.describe()

YEAR       QUARTER         MONTH  DAY_OF_MONTH   DAY_OF_WEEK  \
count  11231.0  11231.000000  11231.000000  11231.000000  11231.000000   
mean    2016.0      2.544475      6.628973     15.790758      3.960199   
std        0.0      1.090701      3.354678      8.782056      1.995257   
min     2016.0      1.000000      1.000000      1.000000      1.000000   
25%     2016.0      2.000000      4.000000      8.000000      2.000000   
50%     2016.0      3.000000      7.000000     16.000000      4.000000   
75%     2016.0      3.000000      9.000000     23.000000      6.000000   
max     2016.0      4.000000     12.000000     31.000000      7.000000   

             FL_NUM  ORIGIN_AIRPORT_ID  DEST_AIRPORT_ID  CRS_DEP_TIME  \
count  11231.000000       11231.000000     11231.000000  11231.000000   
mean    1334.325617       12334.516695     12302.274508   1320.798326   
std      811.875227        1595.026510      1601.988550    490.737845   
min        7.000000       10397.000000     10397.000000     10.000000   
25%      624.000000       10397.000000     10397.000000    905.000000   
50%     1267.000000       12478.000000     12478.000000   1320.000000   
75%     2032.000000       13487.000000     13487.000000   1735.000000   
max     2853.000000       14747.000000     14747.000000   2359.000000   

           DEP_TIME  ...  CRS_ARR_TIME      ARR_TIME     ARR_DELAY  \
count  11124.000000  ...  11231.000000  11116.000000  11043.000000   
mean    1327.189410  ...   1537.312795   1523.978499     -2.573123   
std      500.306462  ...    502.512494    512.536041     39.232521   
min        1.000000  ...      2.000000      1.000000    -67.000000   
25%      905.000000  ...   1130.000000   1135.000000    -19.000000   
50%     1324.000000  ...   1559.000000   1547.000000    -10.000000   
75%     1739.000000  ...   1952.000000   1945.000000      1.000000   
max     2400.000000  ...   2359.000000   2400.000000    615.000000   

          ARR_DEL15     CANCELLED      DIVERTED  CRS_ELAPSED_TIME  \
count  11043.000000  11231.000000  11231.000000      11231.000000   
mean       0.124513      0.010150      0.006589        190.652124   
std        0.330181      0.100241      0.080908         78.386317   
min        0.000000      0.000000      0.000000         93.000000   
25%        0.000000      0.000000      0.000000        127.000000   
50%        0.000000      0.000000      0.000000        159.000000   
75%        0.000000      0.000000      0.000000        255.000000   
max        1.000000      1.000000      1.000000        397.000000   

       ACTUAL_ELAPSED_TIME      DISTANCE  Unnamed: 25  
count         11043.000000  11231.000000          0.0  
mean            179.661233   1161.031965          NaN  
std              77.940399    643.683379          NaN  
min              75.000000    509.000000          NaN  
25%             117.000000    594.000000          NaN  
50%             149.000000    907.000000          NaN  
75%             236.000000   1927.000000          NaN  
max             428.000000   2422.000000          NaN  

[8 rows x 22 columns]

In [6]:
# Handling missing values
dataset.isnull().sum()

YEAR                       0
QUARTER                    0
MONTH                      0
DAY_OF_MONTH               0
DAY_OF_WEEK                0
UNIQUE_CARRIER             0
TAIL_NUM                   0
FL_NUM                     0
ORIGIN_AIRPORT_ID          0
ORIGIN                     0
DEST_AIRPORT_ID            0
DEST                       0
CRS_DEP_TIME               0
DEP_TIME                 107
DEP_DELAY                107
DEP_DEL15                107
CRS_ARR_TIME               0
ARR_TIME                 115
ARR_DELAY                188
ARR_DEL15                188
CANCELLED                  0
DIVERTED                   0
CRS_ELAPSED_TIME           0
ACTUAL_ELAPSED_TIME      188
DISTANCE                   0
Unnamed: 25            11231
dtype: int64

In [7]:
dataset['DEST'].unique()

array(['SEA', 'MSP', 'DTW', 'ATL', 'JFK'], dtype=object)

In [8]:
# Data visualization
sns.scatterplot(dataset['ARR_DELAY'],dataset['ARR_DEL15'])

In [9]:
sns.catplot(x="ARR_DEL15",y="ARR_DELAY",kind='bar',data=dataset)

In [10]:
sns.heatmap(dataset.corr())

In [11]:
# Dropping unnecessary columns
dataset = dataset.drop('Unnamed: 25',axis=1)
dataset.isnull().sum()

YEAR                     0
QUARTER                  0
MONTH                    0
DAY_OF_MONTH             0
DAY_OF_WEEK              0
UNIQUE_CARRIER           0
TAIL_NUM                 0
FL_NUM                   0
ORIGIN_AIRPORT_ID        0
ORIGIN                   0
DEST_AIRPORT_ID          0
DEST                     0
CRS_DEP_TIME             0
DEP_TIME               107
DEP_DELAY              107
DEP_DEL15              107
CRS_ARR_TIME             0
ARR_TIME               115
ARR_DELAY              188
ARR_DEL15              188
CANCELLED                0
DIVERTED                 0
CRS_ELAPSED_TIME         0
ACTUAL_ELAPSED_TIME    188
DISTANCE                 0
dtype: int64

In [12]:
dataset = dataset[["FL_NUM","MONTH","DAY_OF_MONTH","DAY_OF_WEEK","ORIGIN","DEST","CRS_ARR_TIME","DEP_DEL15","ARR_DEL15"]]
dataset.isnull().sum()

FL_NUM            0
MONTH             0
DAY_OF_MONTH      0
DAY_OF_WEEK       0
ORIGIN            0
DEST              0
CRS_ARR_TIME      0
DEP_DEL15       107
ARR_DEL15       188
dtype: int64

In [13]:
# replace missing values with 0 and 1 
dataset = dataset.fillna({'ARR_DEL15':1})
dataset = dataset.fillna({'DEP_DEL15':0})
dataset.iloc[177:185]

FL_NUM  MONTH  DAY_OF_MONTH  DAY_OF_WEEK ORIGIN DEST  CRS_ARR_TIME  \
177    2834      1             9            6    MSP  SEA           852   
178    2839      1             9            6    DTW  JFK          1724   
179      86      1            10            7    MSP  DTW          1632   
180      87      1            10            7    DTW  MSP          1649   
181     423      1            10            7    JFK  ATL          1600   
182     440      1            10            7    JFK  ATL           849   
183     485      1            10            7    JFK  SEA          1945   
184     557      1            10            7    MSP  DTW           912   

     DEP_DEL15  ARR_DEL15  
177        0.0        1.0  
178        0.0        0.0  
179        0.0        1.0  
180        1.0        0.0  
181        0.0        0.0  
182        0.0        0.0  
183        1.0        0.0  
184        0.0        1.0

In [14]:
#Label encoding & One hot encoding

le = LabelEncoder()
dataset['DEST'] = le.fit_transform(dataset['DEST'])
dataset['ORIGIN'] = le.fit_transform(dataset['ORIGIN'])

In [15]:
dataset.head(5)

FL_NUM  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  ORIGIN  DEST  CRS_ARR_TIME  \
0    1399      1             1            5       0     4          2143   
1    1476      1             1            5       1     3          1435   
2    1597      1             1            5       0     4          1215   
3    1768      1             1            5       4     3          1335   
4    1823      1             1            5       4     1           607   

   DEP_DEL15  ARR_DEL15  
0        0.0        0.0  
1        0.0        0.0  
2        0.0        0.0  
3        0.0        0.0  
4        0.0        0.0

In [16]:
oh = OneHotEncoder()
z = oh.fit_transform(dataset[['ORIGIN','DEST']]).toarray()
t = oh.fit_transform(dataset[['DEST','CRS_ARR_TIME']]).toarray()

In [17]:
z

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [18]:
t

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [19]:
#Splitting into dependent and independent variables
dataset = pd.get_dummies(dataset , columns=['ORIGIN','DEST'])
dataset.head()

FL_NUM  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  CRS_ARR_TIME  DEP_DEL15  \
0    1399      1             1            5          2143        0.0   
1    1476      1             1            5          1435        0.0   
2    1597      1             1            5          1215        0.0   
3    1768      1             1            5          1335        0.0   
4    1823      1             1            5           607        0.0   

   ARR_DEL15  ORIGIN_0  ORIGIN_1  ORIGIN_2  ORIGIN_3  ORIGIN_4  DEST_0  \
0        0.0         1         0         0         0         0       0   
1        0.0         0         1         0         0         0       0   
2        0.0         1         0         0         0         0       0   
3        0.0         0         0         0         0         1       0   
4        0.0         0         0         0         0         1       0   

   DEST_1  DEST_2  DEST_3  DEST_4  
0       0       0       0       1  
1       0       0       1       0  
2       0       0       0       1  
3       0       0       1       0  
4       1       0       0       0

In [20]:
x=dataset.drop(columns=['ARR_DEL15']).values

y=dataset['ARR_DEL15'].values

In [21]:
#Splitting into train and test data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
x_test.shape

(2247, 16)

In [23]:
x_train.shape

(8984, 16)

In [24]:
y_test.shape

(2247,)

In [25]:
y_train.shape

(8984,)

In [26]:
#Train and test the model Using Decission tree classifier
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [27]:
classifier = DecisionTreeClassifier(random_state = 0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [28]:
decisiontree = classifier.predict(x_test)

In [29]:
decisiontree

array([1., 0., 0., ..., 0., 0., 1.])

In [30]:
#Predict The Result
decisiontree = classifier.predict(x_test)

In [31]:
decisiontree

array([1., 0., 0., ..., 0., 0., 1.])

In [32]:
#Score Of The Model
desacc = accuracy_score(y_test,decisiontree)

In [33]:
desacc

0.8722741433021807

In [34]:
#Saving Our Model
pickle.dump(classifier,open('flight.pkl','wb'))